#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ble_config_net

include $(IDF_PATH)/make/project.mk
COMPONENT_ADD_INCLUDEDIRS := components/include


